find_path(FLAC_INCLUDE_DIR NAMES FLAC PATHS include)
find_library(FLAC_LIBRARY NAMES FLAC-static PATHS lib )

MESSAGE("** FLAC FOUND BY CONAN")
SET(FLAC_FOUND TRUE)
MESSAGE("** FOUND FLAC:  ${FLAC_LIBRARY}")
MESSAGE("** FOUND FLAC INCLUDE:  ${FLAC_INCLUDE_DIR}")

set(FLAC_INCLUDE_DIRS ${FLAC_INCLUDE_DIR})
set(FLAC_LIBRARIES ${FLAC_LIBRARY})

mark_as_advanced(FLAC_LIBRARY FLAC_INCLUDE_DIR)

set(FLAC_MAJOR_VERSION "1")
set(FLAC_MINOR_VERSION "3")
set(FLAC_PATCH_VERSION "1")
